#!/usr/bin/env python3
import gi

gi.require_version("Gtk", "4.0")
gi.require_version("Adw", "1")
import os
import platform
import subprocess
import sys

from gi.repository import Adw
from akstaging.window import AkamaiStagingWindow


class AkamaiApp(Adw.Application):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.window = None  # Store a reference to the main window
        self.connect("activate", self.on_activate)

    def on_activate(self, app):
        self.style_manager = Adw.StyleManager.get_default()
        # self.style_manager.set_color_scheme(Adw.ColorScheme.FORCE_DARK)

        if not self.window:  # Only create a new window if there isn't one
            self.window = AkamaiStagingWindow(application=app)
            self.window.present()


def is_root():
    return os.geteuid() == 0


def escalate_privileges_linux():
    print("Requesting root privileges on Linux...")
    sudo_command = ["sudo", sys.executable] + sys.argv
    os.execvp("sudo", sudo_command)


def escalate_privileges_mac():
    print("Requesting root privileges on macOS...")
    script = f'do shell script "{sys.executable} {os.path.abspath(sys.argv[0])}" with administrator privileges'
    subprocess.call(["osascript", "-e", script])
    sys.exit(0)


if __name__ == "__main__":
    print("Starting application...")
    if not is_root():
        if platform.system() == "Linux":
            # escalate_privileges_linux()
            print("User not root on linux")
        elif platform.system() == "Darwin":
            escalate_privileges_mac()
        else:
            raise OSError("Unsupported operating system for privilege escalation")
    else:
        print("Escalated privileges to write to /etc/hosts.")
        app = AkamaiApp(application_id="com.github.mclellac.AkamaiStaging")
        app.run(sys.argv)
